AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Creats a CloudWatch Log Group for the CloudTrail logs

Metadata:
  Identifier: cw-mf-LogGroup
  CreatedOn: 2021/08/08
  CreatedBy: Nick The Security Dude

Parameters:

  pLogGroupName:
    Type: String

Resources:

  # CloudWatch Log Group
  rCISLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      KmsKeyId: !Join
        - ''
        - - !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/
          - '{{resolve:ssm:/cloudwatch/metricfilter/cis/key:1}}'
      LogGroupName: !Ref pLogGroupName
      RetentionInDays: 60


