AWSTemplateFormatVersion: '2010-09-09'

Description: >-
  Creates an SNS Topic for the Metric Alarms

Metadata:
  Identifier: cw-mf-MetricFilter
  CreatedOn: 2021/08/08
  CreatedBy: Nick The Security Dude

Parameters:

  pSNSAlarmTopicName:
    Type: String

Resources:

  # SNS Alarm Topic
  rCISSNSAlarmTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: !Ref pSNSAlarmTopicName

